### ISSUE TITLE
faust~ crash when no argument is given

### ISSUE THREAD

**Issue by alfonso73** [pierreguillot/faust-pd#1]
Hi @pierreguillot !
Great stuff here!
I don't understand very good from the readme if the LLVM binaries would work for Win64 to. If not where i can find the sources and the how-to for building?
best!
ps. you're really givin' PD some serious gold! better said diamonds!

**Comment by pierreguillot** [comment]
Thanks 😄 
Yes, in fact for the moment LLVM binaries work only for Windows 64 bits with Pd 64 bits. I have difficulties to compile the proper LLVM/faust libraries for Pd 32 bits on my 64 bits machine. Anyway, you can already try the pre-release external if you want: [releases](https://github.com/pierreguillot/faust-pd/releases).
Cheers

**Comment by alfonso73** [comment]
thanks pierre. So let me understand i only need to install the stuff inside the release .zip? Or do i have to install this  http://releases.llvm.org/5.0.2/LLVM-5.0.2-win64.exe before?

**Comment by pierreguillot** [comment]
You don't need to install anything (normally), just unzip the folder and open the help file

**Comment by alfonso73** [comment]
Thanks! The help works perfectly. But if i instantiate a [faust~] PD suddenly quits. Maybe there's no guard check if the object is instantiated without specifing a .dsp file?

ps...BTW thinkin' when this will come to Camomile ...wow!

**Comment by pierreguillot** [comment]
> Maybe there's no guard check if the object is instantiated without specifing a .dsp file?

Yes, indeed. I will fix this!

**Comment by pierreguillot** [comment]
Fixed, now `[faust~]`is valid but does nothing - you must give a valid file.
