### ISSUE TITLE
Compiling with LLVM 10

### ISSUE THREAD

**Issue by agraef** [pierreguillot/faust-pd#8]
Hi Pierre, it's been a while, I hope you're well!

I'm currently trying to get faustgen~ to work on Arch, which has LLVM 10.0.0 now. The Faust version included as a submodule in faustgen is pretty old (Aug 2018, somewhere around Faust 2.8.4), which doesn't compile with LLVM 10. This begins already with the regex used to parse LLVM version numbers in the Faust cmake configuration, which is completely thrown off by 2-digit version numbers. ;-)

I was able to get that version to compile by messing quite a bit with the Faust source, the required patch is included below. I *could* package up faustgen~ for Arch that way, by just applying that patch when building the package. But I guess that the proper way forward is to just update faustgen~ so that it uses a more recent Faust version.

2.20.2 is the most recent stable release, but unfortunately it seems that even that still needs to be patched up with the following two commits from Dec 2019 (one of these two is the LLVM 10 support which was contributed by Jean-Michaël Celerier, yeah, the guy from Université de Bordeaux who's organizing LAC this year ;-):

https://github.com/grame-cncm/faust/commit/0bbc3e4b605d3cec5e8fa17162b342e761ae9a1a
https://github.com/grame-cncm/faust/commit/10a35c5341c110b7dcdd5310f46bb357605420d1

(I know that because that's how David Runge builds the Faust package in the Arch community repositories, you can find his latest PKGBUILD here: https://github.com/archlinux/svntogit-community/blob/packages/faust/trunk/PKGBUILD.)

Anyway, we can always wait for the next stable Faust release, which should hopefully compile OOTB with LLVM 10. I just wanted to give you a quick heads up so that you know that an update of the Faust submodule may be in order rather sooner than later. What do you think?

**Comment by agraef** [comment]
And just for the record, here's the patch for the faust submodule (at https://github.com/grame-cncm/faust/commit/341bd3c562b4dcb9271a82bc939313613bc59244) that I needed to apply to the current HEAD to make the faustgen~ source build with LLVM 10.0.0. (GH doesn't allow me to attach diffs, so I'm just inlining it here.)

~~~diff
diff --git a/build/CMakeLists.txt b/build/CMakeLists.txt
index e4d12e08d..be0590395 100644
--- a/build/CMakeLists.txt
+++ b/build/CMakeLists.txt
@@ -181,13 +181,17 @@ if (INCLUDE_LLVM )
 		endif()
 	endif()
 
-	string (REGEX REPLACE "([0-9])\\.([0-9]).*" "LLVM_\\1\\2" LLVM_VERSION ${LLVM_PACKAGE_VERSION})
+	string (REGEX REPLACE "([0-9]+)\\.([0-9]+).*" "LLVM_\\1\\2" LLVM_VERSION ${LLVM_PACKAGE_VERSION})
 
 	# the declarations below are redundant but necessary to cope with different cmake behaviors on different platforms
 	set (TMP ${SRCDIR}/generator/llvm)
 	set_property(SOURCE ${TMP}/llvm_dsp_aux.cpp ${TMP}/llvm_dynamic_dsp_aux.cpp APPEND_STRING PROPERTY COMPILE_FLAGS "-fno-rtti ${LLVM_DEFINITIONS}")
 	set_property(SOURCE ${TMP}/llvm_dsp_aux.cpp ${TMP}/llvm_dynamic_dsp_aux.cpp APPEND_STRING PROPERTY CMAKE_CXX_FLAGS "-fno-rtti ${LLVM_DEFINITIONS}")
 	set (FAUST_LIBS ${FAUST_LIBS} ${LLVM_LD_FLAGS} ${LLVM_LIBS})
+
+	if("${LLVM_PACKAGE_VERSION}" VERSION_GREATER_EQUAL 10)
+         set (CMAKE_CXX_STANDARD 14)
+	endif()
 endif()
 
 ####################################
diff --git a/compiler/generator/llvm/llvm_code_container.cpp b/compiler/generator/llvm/llvm_code_container.cpp
index ae88a24d9..60af94672 100644
--- a/compiler/generator/llvm/llvm_code_container.cpp
+++ b/compiler/generator/llvm/llvm_code_container.cpp
@@ -68,7 +68,7 @@ LLVMCodeContainer::LLVMCodeContainer(const string& name, int numInputs, int numO
 
     // Set "-fast-math"
     FastMathFlags FMF;
-#if defined(LLVM_60)
+#if defined(LLVM_60) || defined(LLVM_70) || defined(LLVM_80) || defined(LLVM_90) || defined(LLVM_100)
     FMF.setFast();  // has replaced the below function
 #else
     FMF.setUnsafeAlgebra();
@@ -98,7 +98,7 @@ LLVMCodeContainer::LLVMCodeContainer(const string& name, int numInputs, int numO
 
     // Set "-fast-math"
     FastMathFlags FMF;
-#if defined(LLVM_60)
+#if defined(LLVM_60) || defined(LLVM_70) || defined(LLVM_80) || defined(LLVM_90) || defined(LLVM_100)
     FMF.setFast();  // has replaced the below function
 #else
     FMF.setUnsafeAlgebra();
@@ -220,7 +220,7 @@ void LLVMCodeContainer::generateComputeBegin(const string& counter)
         Function::Create(llvm_compute_type, GlobalValue::ExternalLinkage, "compute" + fKlassName, fModule);
     llvm_compute->setCallingConv(CallingConv::C);
 
-#if !defined(LLVM_50) && !defined(LLVM_60)
+#if !defined(LLVM_50) && !defined(LLVM_60) && !defined(LLVM_70) && !defined(LLVM_80) && !defined(LLVM_90) && !defined(LLVM_100)
     llvm_compute->setDoesNotAlias(3U);
     llvm_compute->setDoesNotAlias(4U);
 #endif
diff --git a/compiler/generator/llvm/llvm_dsp_aux.cpp b/compiler/generator/llvm/llvm_dsp_aux.cpp
index 725a5d248..4a3e077e4 100644
--- a/compiler/generator/llvm/llvm_dsp_aux.cpp
+++ b/compiler/generator/llvm/llvm_dsp_aux.cpp
@@ -37,7 +37,7 @@
 #include <llvm/Support/FileSystem.h>
 #include <llvm/Support/TargetSelect.h>
 
-#if defined(LLVM_40) || defined(LLVM_50) || defined(LLVM_60)
+#if defined(LLVM_40) || defined(LLVM_50) || defined(LLVM_60) || defined(LLVM_70) || defined(LLVM_80) || defined(LLVM_90) || defined(LLVM_100)
 #include <llvm/Bitcode/BitcodeReader.h>
 #include <llvm/Bitcode/BitcodeWriter.h>
 #else
diff --git a/compiler/generator/llvm/llvm_dynamic_dsp_aux.cpp b/compiler/generator/llvm/llvm_dynamic_dsp_aux.cpp
index df0b590f6..c20e7b7db 100644
--- a/compiler/generator/llvm/llvm_dynamic_dsp_aux.cpp
+++ b/compiler/generator/llvm/llvm_dynamic_dsp_aux.cpp
@@ -73,7 +73,7 @@
 #include <llvm/Target/TargetLibraryInfo.h>
 #endif
 
-#if defined(LLVM_40) || defined(LLVM_50) || defined(LLVM_60)
+#if defined(LLVM_40) || defined(LLVM_50) || defined(LLVM_60) || defined(LLVM_70) || defined(LLVM_80) || defined(LLVM_90) || defined(LLVM_100)
 #include <llvm/Bitcode/BitcodeReader.h>
 #include <llvm/Bitcode/BitcodeWriter.h>
 #include <llvm/Transforms/IPO/AlwaysInliner.h>
@@ -82,6 +82,11 @@
 #include <llvm/Support/raw_ostream.h>
 #endif
 
+#if defined(LLVM_100)
+#include <llvm/InitializePasses.h>
+#include <llvm/Support/CodeGen.h>
+#endif
+
 using namespace llvm;
 using namespace std;
 
@@ -118,7 +123,7 @@ static bool isParam(int argc, const char* argv[], const string& param)
     return false;
 }
 
-#if defined(LLVM_40) || defined(LLVM_50) || defined(LLVM_60)
+#if defined(LLVM_40) || defined(LLVM_50) || defined(LLVM_60) || defined(LLVM_70) || defined(LLVM_80) || defined(LLVM_90) || defined(LLVM_100)
 static Module* ParseBitcodeFile(MEMORY_BUFFER Buffer, LLVMContext& Context, string* ErrMsg)
 {
     using namespace llvm;
@@ -162,7 +167,11 @@ void llvm_dynamic_dsp_factory_aux::write(std::ostream* out, bool binary, bool sm
     string             res;
     raw_string_ostream out_str(res);
     if (binary) {
+#if defined(LLVM_70) || defined(LLVM_80) || defined(LLVM_90) || defined(LLVM_100)
+        WriteBitcodeToFile(*fModule, out_str);
+#else
         WriteBitcodeToFile(fModule, out_str);
+#endif
     } else {
         out_str << *fModule;
     }
@@ -174,7 +183,11 @@ string llvm_dynamic_dsp_factory_aux::writeDSPFactoryToBitcode()
 {
     string             res;
     raw_string_ostream out(res);
+#if defined(LLVM_70) || defined(LLVM_80) || defined(LLVM_90) || defined(LLVM_100)
+    WriteBitcodeToFile(*fModule, out);
+#else
     WriteBitcodeToFile(fModule, out);
+#endif
     out.flush();
     return base64_encode(res);
 }
@@ -183,7 +196,11 @@ void llvm_dynamic_dsp_factory_aux::writeDSPFactoryToBitcodeFile(const string& bi
 {
     STREAM_ERROR   err;
     raw_fd_ostream out(bit_code_path.c_str(), err, sysfs_binary_flag);
+#if defined(LLVM_70) || defined(LLVM_80) || defined(LLVM_90) || defined(LLVM_100)
+    WriteBitcodeToFile(*fModule, out);
+#else
     WriteBitcodeToFile(fModule, out);
+#endif
 }
 
 // IR
@@ -234,7 +251,7 @@ static void AddOptimizationPasses(PassManagerBase& MPM, FUNCTION_PASS_MANAGER& F
         }
         Builder.Inliner = createFunctionInliningPass(Threshold);
     } else {
-#if defined(LLVM_40) || defined(LLVM_50) || defined(LLVM_60)
+#if defined(LLVM_40) || defined(LLVM_50) || defined(LLVM_60) || defined(LLVM_70) || defined(LLVM_80) || defined(LLVM_90) || defined(LLVM_100)
         Builder.Inliner = createAlwaysInlinerLegacyPass();
 #else
         Builder.Inliner = createAlwaysInlinerPass();
@@ -317,7 +334,7 @@ bool llvm_dynamic_dsp_factory_aux::initJIT(string& error_msg)
 
         builder.setOptLevel(CodeGenOpt::Aggressive);
         builder.setEngineKind(EngineKind::JIT);
-#if !defined(LLVM_60)
+#if !defined(LLVM_60) && !defined(LLVM_70) && !defined(LLVM_80) && !defined(LLVM_90) && !defined(LLVM_100)
         builder.setCodeModel(CodeModel::JITDefault);
 #endif
 
@@ -348,7 +365,7 @@ bool llvm_dynamic_dsp_factory_aux::initJIT(string& error_msg)
 
         // -fastmath is activated at IR level, and has to be setup at JIT level also
 
-#if !defined(LLVM_50) && !defined(LLVM_60)
+#if !defined(LLVM_50) && !defined(LLVM_60) && !defined(LLVM_70) && !defined(LLVM_80) && !defined(LLVM_90) && !defined(LLVM_100)
         targetOptions.LessPreciseFPMADOption = true;
 #endif
         targetOptions.AllowFPOpFusion       = FPOpFusion::Fast;
@@ -357,7 +374,7 @@ bool llvm_dynamic_dsp_factory_aux::initJIT(string& error_msg)
         targetOptions.NoNaNsFPMath          = true;
         targetOptions.GuaranteedTailCallOpt = true;
 
-#if defined(LLVM_40) || defined(LLVM_50) || defined(LLVM_60)
+#if defined(LLVM_40) || defined(LLVM_50) || defined(LLVM_60) || defined(LLVM_70) || defined(LLVM_80) || defined(LLVM_90) || defined(LLVM_100)
         targetOptions.NoTrappingFPMath = true;
         targetOptions.FPDenormalMode   = FPDenormal::IEEE;
 #endif
@@ -410,7 +427,7 @@ bool llvm_dynamic_dsp_factory_aux::initJIT(string& error_msg)
             }
 
             if ((debug_var != "") && (debug_var.find("FAUST_LLVM1") != string::npos)) {
-#if defined(LLVM_60)
+#if defined(LLVM_60) || defined(LLVM_70) || defined(LLVM_80) || defined(LLVM_90) || defined(LLVM_100)
             // TargetRegistry::printRegisteredTargetsForVersion(std::cout);
 #else
             TargetRegistry::printRegisteredTargetsForVersion();
@@ -427,7 +444,7 @@ bool llvm_dynamic_dsp_factory_aux::initJIT(string& error_msg)
             pm.add(createVerifierPass());
 
             if ((debug_var != "") && (debug_var.find("FAUST_LLVM4") != string::npos)) {
-#if defined(LLVM_38) || defined(LLVM_39) || defined(LLVM_40) || defined(LLVM_50) || defined(LLVM_60)
+#if defined(LLVM_38) || defined(LLVM_39) || defined(LLVM_40) || defined(LLVM_50) || defined(LLVM_60) || defined(LLVM_70) || defined(LLVM_80) || defined(LLVM_90) || defined(LLVM_100)
             // TODO
 #else
             tm->addPassesToEmitFile(pm, fouts(), TargetMachine::CGFT_AssemblyFile, true);
diff --git a/compiler/generator/llvm/llvm_instructions.hh b/compiler/generator/llvm/llvm_instructions.hh
index c1147950d..b9f230f53 100644
--- a/compiler/generator/llvm/llvm_instructions.hh
+++ b/compiler/generator/llvm/llvm_instructions.hh
@@ -58,7 +58,7 @@
 #include <llvm/Support/raw_ostream.h>
 #include <llvm/Transforms/Scalar.h>
 
-#if defined(LLVM_40) || defined(LLVM_50) || defined(LLVM_60)
+#if defined(LLVM_40) || defined(LLVM_50) || defined(LLVM_60) || defined(LLVM_70) || defined(LLVM_80) || defined(LLVM_90) || defined(LLVM_100)
 #include <llvm/Bitcode/BitcodeReader.h>
 #include <llvm/Bitcode/BitcodeWriter.h>
 #else
~~~

**Comment by sletz** [comment]
In case it helps, we have a Faust 2.27.2 pre-release with LLVM 10 support here https://github.com/grame-cncm/faust/releases.

**Comment by agraef** [comment]
Yes, @sletz I noticed this, too, but it has a big sticker NOT TO BE PACKAGED all over it. ;-)

**Comment by agraef** [comment]
Well, we might use this for testing and then just switch to 2.27.2 proper when it comes out. But it seems that @pierreguillot is on vacation anyway, so let's just wait and see what his thoughts are.

**Comment by sletz** [comment]
Release 2.27.1 done: https://github.com/grame-cncm/faust/releases. Time for vacation.

**Comment by agraef** [comment]
So this has LLVM 10 support? There's nothing in the release notes about that.

In any case, @sletz, have a nice vacation! I'm on vacation as well. ;-)

**Comment by sletz** [comment]
Yes, and just fixed that.

**Comment by agraef** [comment]
@pierreguillot, for the time being I've uploaded an initial PKGBUILD to the Arch User Repositories (AUR) here: https://aur.archlinux.org/packages/pd-faustgen/. This is for the 0.1.1 version, so it includes the patch from above to make it compile with LLVM 10.

I've noticed that you already started working on a new branch, great! I will test that asap, and once it's finished, I'll update the AUR package.

**Comment by agraef** [comment]
Just tested the dev/v0.1.2 branch which seems to work pretty well already. Compilation goes through on Arch alright, but then it fails during linking with the following error message:

~~~shell
[ 98%] Linking C shared library "../external/faustgen~.pd_linux"
/usr/bin/cmake -E cmake_link_script CMakeFiles/faustgen_tilde_project.dir/link.txt --verbose=1
/usr/bin/cc -fPIC   -shared -Wl,-soname,faustgen~.pd_linux -o "../external/faustgen~.pd_linux" CMakeFiles/faustgen_tilde_project.dir/src/faust_tilde_io.c.o CMakeFiles/faustgen_tilde_project.dir/src/faust_tilde_options.c.o CMakeFiles/faustgen_tilde_project.dir/src/faust_tilde_ui.c.o CMakeFiles/faustgen_tilde_project.dir/src/faustgen_tilde.c.o  ../faust/build/lib/libfaust.a /usr/lib/libLLVMSupport.a /usr/lib/libLLVMCore.a /usr/lib/libLLVMIRReader.a -lLLVMjit /usr/lib/libLLVMX86CodeGen.a /usr/lib/libLLVMX86AsmParser.a /usr/lib/libLLVMX86Desc.a /usr/lib/libLLVMX86Disassembler.a /usr/lib/libLLVMX86Info.a /usr/lib/libLLVMX86Utils.a -lstdc++ -L/usr/lib -lLLVM-10 /usr/lib/libLLVMAsmParser.a /usr/lib/libLLVMAsmPrinter.a /usr/lib/libLLVMDebugInfoDWARF.a /usr/lib/libLLVMCFGuard.a /usr/lib/libLLVMGlobalISel.a /usr/lib/libLLVMSelectionDAG.a /usr/lib/libLLVMCodeGen.a /usr/lib/libLLVMBitWriter.a /usr/lib/libLLVMScalarOpts.a /usr/lib/libLLVMAggressiveInstCombine.a /usr/lib/libLLVMInstCombine.a /usr/lib/libLLVMTransformUtils.a /usr/lib/libLLVMTarget.a /usr/lib/libLLVMAnalysis.a /usr/lib/libLLVMProfileData.a /usr/lib/libLLVMObject.a /usr/lib/libLLVMBitReader.a /usr/lib/libLLVMCore.a /usr/lib/libLLVMRemarks.a /usr/lib/libLLVMBitstreamReader.a /usr/lib/libLLVMTextAPI.a /usr/lib/libLLVMMCParser.a /usr/lib/libLLVMMCDisassembler.a /usr/lib/libLLVMMC.a /usr/lib/libLLVMBinaryFormat.a /usr/lib/libLLVMDebugInfoCodeView.a /usr/lib/libLLVMDebugInfoMSF.a /usr/lib/libLLVMSupport.a -lz -lrt -ldl -ltinfo -lpthread -lm /usr/lib/libLLVMDemangle.a 
/usr/bin/ld: cannot find -lLLVMjit
collect2: error: ld returned 1 exit status
~~~

Maybe an issue with the LLVM 10 cmake configuration?

**Comment by pierreguillot** [comment]
Hello Albert and Stéphane,

I'm fine and I hope you're well too! 
Indeed, I started to have a look at this issue and I encountered a problem when linking LLVM.  In the CmakeList.txt, I replaced 
`llvm_map_components_to_libnames(llvm_libs all)` that doesn't work anymore (llvm_libs was empty) by `llvm_map_components_to_libnames(llvm_libs support core irreader engine)` (I'm not sure of the components to use so I put some of them just to check if the method was still working and if it is the *all* argument that is not valid anymore and indeed the *all* argument seems nott valid anymore - now I should ask Stephane which ones to use exactly...). Anyway, now, it seems that LLVMjitt is not found (and I guess that should be necessary for Faust), I will try to recompile LLVM manually (perhaps this lib is not shipped with the pre-built version?). For the moment, it was just a quick test but I have to further investigate the changes since LLVM 8...

**Comment by agraef** [comment]
Hi Pierre, great to hear from you! Well, you're pretty close already, getting the required LLVM libs sorted out shouldn't be that hard. In fact, I think that just linking against libLLVM-10.so should be enough (at least that's what /usr/lib/libfaust.so links against over here), and you already got that in your link line. We just need to get rid of all the rest. ;-) I'm not sure how well that will work on Mac and Windows, though, but we can start worrying about that once we've got the Linux version working.

I'm taking a look at the source myself right now, as there are also some things I'd like to add -- like dumping a list of all parameters and the metadata (not just printing them in the Pd console), as well as OSC, MIDI and polyphony support, which are still needed to bring pd-faustgen up to par with Stephane's Max/MSP faustgen and my own pd-faust. The dynamic Pd GUI generator is still something that only pd-faust offers right now, but I can probably replace that with something written in Lua (using [Pd-Lua](https://agraef.github.io/pd-lua/)).

I'd really like to get rid of pd-faust at some point and use pd-faustgen instead. It's the way forward, as pd-faust still uses the ancient LLVM 3.5, which gives me a lot of trouble nowadays. (It just crashes Pd when trying to use any external that depends on the system LLVM in some way, such as Gem.)

**Comment by agraef** [comment]
But to get back to the linker issue, I don't see why the original line, `llvm_map_components_to_libnames(llvm_libs all)`, would have to be changed, since it seems to work fine when linking the master branch against LLVM 10 (after applying the patch to bring LLVM 10 compatibility to the old Faust snapshot). Let me give that a try.

**Comment by agraef** [comment]
Works fine over here (using the LLVM 10 package from the official Arch repos, that is). More precisely, if I just take dev/v0.1.2 as it is, and change back that one line to:

~~~cmake
llvm_map_components_to_libnames(llvm_libs all)
~~~

The build then runs through just fine, no hitches during linking. The binaries also work (tested by running faustgen~-help.pd in Purr Data).

Here's the link line reported by running `make VERBOSE=1`:

~~~shell
/usr/bin/cc -fPIC   -shared -Wl,-soname,faustgen~.pd_linux -o "../external/faustgen~.pd_linux" CMakeFiles/faustgen_tilde_project.dir/src/faust_tilde_io.c.o CMakeFiles/faustgen_tilde_project.dir/src/faust_tilde_options.c.o CMakeFiles/faustgen_tilde_project.dir/src/faust_tilde_ui.c.o CMakeFiles/faustgen_tilde_project.dir/src/faustgen_tilde.c.o  ../faust/build/lib/libfaust.a -lpthread -lstdc++ -L/usr/lib -lLLVM-10
~~~

Much tidier, it only links against libLLVM-10.so, as it should. So for me rev. 3d2d282a7ffedb0be28bd392e20eae4d76e91af9 actually *broke* things and should probably be reverted. Maybe there's an issue with your LLVM 10 installation in Travis which tripped the linker problems with rev. 0a5d578a8816c58a1427e1609f844e3e075b7d06?

Anyway, this means that I should be able to create a working package by just going back to rev. 0a5d578a8816c58a1427e1609f844e3e075b7d06.

**Comment by agraef** [comment]
Yep, rev. 0a5d578a8816c58a1427e1609f844e3e075b7d06 does it, so I updated the pd-faustgen-git package on the AUR accordingly: https://aur.archlinux.org/packages/pd-faustgen-git/

Anyway, once v0.1.2 is out, I'll see whether we can get @dvzrv from the Arch proaudio team on board to take over and improve my pd-faustgen package, so that it becomes officially available in the Arch community repositories.

**Comment by pierreguillot** [comment]
On Travis CI, I use the LLVM pre-built 10.0.0 (https://github.com/llvm/llvm-project/releases/download/llvmorg-10.0.0/clang+llvm-10.0.0-x86_64-linux-gnu-ubuntu-18.04.tar.xz and https://github.com/llvm/llvm-project/releases/download/llvmorg-10.0.0/clang+llvm-10.0.0-x86_64-apple-darwin.tar.xz). Then using `llvm_map_components_to_libnames(llvm_libs all)`, the CI fails in CMakeList.txt because `llvm_libs` is empty when calling `list(REMOVE_ITEM llvm_libs LTO)`. But if we just have to link against libLLVM, perhaps we could remove these lines. I only have to ensure that it works fine on mac and windows too. I'm on holidays so I'll have time to work on it the next weeks :)

**Comment by pierreguillot** [comment]
For macOS, there is no libLLVM-10 in the pre-built package. I managed to link against 'all' again using `llvm_map_components_to_libnames(llvm_libs ${LLVM_TARGETS_TO_BUILD}) ` (that seems to include all the libs) but there are still unresolved symbols at runtime:
```
tried .../pd-faustgen/external/faustgen~.pd_darwin and succeeded
.../pd-faustgen/external/faustgen~.pd_darwin: dlopen(/.../pd-faustgen/external/faustgen~.pd_darwin, 10): Symbol not found: __ZN4llvm11ObjectCache6anchorEv
  Referenced from: .../pd-faustgen/external/faustgen~.pd_darwin
  Expected in: flat namespace
 in .../pd-faustgen/external/faustgen~.pd_darwin
```

**Comment by agraef** [comment]
That's unfortunate. So maybe they always distribute LLVM as static libs only. But even then `llvm_map_components_to_libnames(llvm_libs all)` is supposed to work. At least I think so; what little documentation I could find about LLVM's cmake build system on llvm.org doesn't say so, it only talks about building llvm itself.

In any case, the component specifier `all` *is* recognized, I can see that looking at the definition of `llvm_map_components_to_libnames`, in LLVM-Config.cmake line 269. If it gives an empty list of libs, then IMHO that's a bug in the cmake configuration, so either they botched that release, or their cmake config is broken in some way, or both. Oh well. It's not the first botched LLVM package, I've seen many over the years. It's a bit disturbing, though, that something like that slips through LLVM's own CI.

One thing you might still try is to run the shell command `llvm-config --libs all` instead. At least on my system that gives me the proper link options (`-lLLVM-10`). But if `llvm_map_components_to_libnames` is broken, `llvm-config` might well be broken, too.

So LLVM 10 seems to be a no-go on Travis for now. I'd suggest to revert *both* rev. 3d2d282a7ffedb0be28bd392e20eae4d76e91af9 and c4bd14f73acd08bda13f850e40ebef601843ab0a, and just go back to the LLVM version that you were using before. AFAICT, the version in https://github.com/CICM/pd-faustgen/releases/tag/v0.0.0 should be LLVM 5, right? With a bit of luck, that should still be recent enough to build current Faust. And we already know that that version builds fine with LLVM 10 on Arch at least.

**Comment by agraef** [comment]
I've got that source in my testing branch over at https://github.com/agraef/pd-faustgen/tree/testing now, where I simply got rid of rev. 3d2d282 and c4bd14f entirely. You could just pull that branch over to your repo and check whether it compiles ok in Travis, check that it compiles in Windows, too, and release it as v0.1.2.

**Comment by pierreguillot** [comment]
I dropped the commit but it fails on [mac](https://travis-ci.org/github/CICM/pd-faustgen/jobs/714406424) and [Windows](https://ci.appveyor.com/project/CICM/pd-faustgen/builds/34447214) and the link for LLVM-5 pre-built has changed so it doesn't compile on [Linux](https://travis-ci.org/github/CICM/pd-faustgen/jobs/714406425). This last problem can easily be fixed but it seems that the Faust 2.27.2 is not compatible with LLVM-5 on Windows and Mac...

**Comment by pierreguillot** [comment]
Using LLVM-9.0.0 with Faust v2.27.2 seems to work on Linux and Mac so I'll try with this version. But I think I have to create a new LLVM package for Windows. Once it compiles on Windows I can create a new release v0.1.2. For the other requests can you create new issues and/or MRs?

**Comment by agraef** [comment]
You mean dump, OSC, MIDI and polyphony support? Yes sure, will do.

**Comment by pierreguillot** [comment]
Great thanks! I managed to compile against LLVM-9.0.0 on Windows with Faust v2.27.2 so I will setup the CI with the new LLVM pre-built and prepare a new release 0.1.2. Then we could start a GitHub project for 0.2.0 with your requests, does it sound good to you?

**Comment by pierreguillot** [comment]
Everything seems to work! If the branch [dev/v0.1.2](https://github.com/CICM/pd-faustgen/tree/dev/v0.1.2) is good for you I will [merge](https://github.com/CICM/pd-faustgen/pull/9) it into master.

**Comment by agraef** [comment]
Sounds great! @sletz, is there some documentation about faustgen somewhere, specifically about its polyphony and OSC support?

**Comment by sletz** [comment]
Maybe here: https://github.com/grame-cncm/faust/tree/master-dev/embedded/faustgen

**Comment by agraef** [comment]
Oops, sorry, I should have been able to find that myself. ;-)

**Comment by agraef** [comment]
@pierreguillot I just tested again with the latest dev/v0.1.2 and it still builds fine with LLVM 10 on Arch. As soon as you've merged into master, I'll update my AUR packages.

For a proper Arch package, we'll probably need a complete tarball, though, submodules included. Do you know how to do this? Something like this: https://github.com/grame-cncm/faust/blob/HEAD/Makefile#L205 (that's the `dist` target in Faust's toplevel Makefile; sorry, I'm not sure how to add a target like this to the cmake config).

**Comment by pierreguillot** [comment]
No, I've no idea of the proper way to do that. Do you really need a new target? Perhaps, we add a simple bash script to do that and create a new artefact on the Linux CI when there is a tag? Do you want to do that for v0.1.2? I close this issue and we can create another one for this specific question.

**Comment by agraef** [comment]
No, a bash script would be fine. I can write one and submit it as a PR. Stay tuned.

**Comment by agraef** [comment]
See https://github.com/CICM/pd-faustgen/pull/10.
